<!DOCTYPE html>

<head>
    <title>JavaScript</title>
</head>

<body>
    <h1>JavaScript error handling using promise
    </h1>
    <script>
        const cart = ["shoes", "pants", "kurta"];

        createOrder(cart)
        .then(function(orderId){
            console.log(orderId);
            return orderId;   
        })
        .catch(function (err){
            console.log(err.message);
        })
        .then(function(orderId){
            proceedToPayment(orderId);
        })
        .then(function(paymentInfo){
            console.log(paymentInfo);
        })
        .catch(function(err){
            console.log(err.message);
        })
        .then(function(orderId){
            console.log("no matter what this will be called")
        });

        //producer

        function createOrder(cart){
            const pr = new Promise(function(resolve, reject){
                //createOrder
                //validateCart
                //orderId
                if (!validateCart(cart)) {
                    const err = new Error("Cart is not valid");
                    reject(err);
                }
                //logic for createOrder
                const orderId = "12345"
                if (orderId) {
                    setTimeout(function (){
                        resolve(orderId);
                    }, 5000);
                    
                }
            });
            return pr;
        }
        function validateCart(cart){
            return true;
        }

        function proceedToPayment(orderId) {
            return new Promise(function(resolve, reject){
                resolve("payment successful");
            });
        }
    </script>
</body>

</html>